export const MENU_ITEMS = [
  { cat: "CORE", name: "Overview", path: "/dashboard/overview", color: "text-cyan-400" },
  { cat: "PROTECTION", name: "Divine Intervention (D.i.T.)", path: "/dashboard/god-mode", color: "text-yellow-500" },
  { cat: "PROTECTION", name: "Law Bots", path: "/dashboard/law-bots", color: "text-blue-500" },
  { cat: "PROTECTION", name: "Family Shield", path: "/dashboard/family-shield", color: "text-blue-400" },
  { cat: "PROTECTION", name: "Legal Defense", path: "/dashboard/legal-defense", color: "text-blue-300" },
  { cat: "MESH OPS", name: "Mesh Ingest", path: "/dashboard/mesh-ingest", color: "text-cyan-400" },
  { cat: "MESH OPS", name: "Mesh List", path: "/dashboard/mesh-list", color: "text-blue-400" },
  { cat: "MESH OPS", name: "Mesh Sync", path: "/dashboard/mesh-sync", color: "text-green-400" },
  { cat: "MESH OPS", name: "Partition Maint", path: "/dashboard/partition-maintenance", color: "text-orange-400" },
  { cat: "MESH OPS", name: "Meta Index", path: "/dashboard/scrollchain-meta-index", color: "text-purple-400" },
  { cat: "MESH OPS", name: "Solar Lead", path: "/dashboard/scrollchain-solar-lead", color: "text-yellow-400" },
  { cat: "MESH OPS", name: "Events", path: "/dashboard/scrollchain-events", color: "text-pink-400" },
  { cat: "MESH OPS", name: "Audit", path: "/dashboard/scrollchain-audit", color: "text-red-400" },
  { cat: "MESH OPS", name: "Health", path: "/dashboard/scrollchain-health", color: "text-green-500" },
  { cat: "MESH OPS", name: "Topology", path: "/dashboard/mesh-topology", color: "text-blue-200" },
  { cat: "MESH OPS", name: "Policy Check", path: "/dashboard/mesh-policy-check", color: "text-red-300" },
  { cat: "MESH OPS", name: "Badge", path: "/dashboard/mesh-badge", color: "text-yellow-200" },
  { cat: "MESH OPS", name: "Subscriber Poller", path: "/dashboard/mesh-subscriber-poller", color: "text-cyan-500" },
  { cat: "MESH OPS", name: "NATS Helper", path: "/dashboard/_shared_nats_helper", color: "text-gray-400" },
  { cat: "MESH OPS", name: "Outbox Processor", path: "/dashboard/nats-outbox-processor", color: "text-purple-300" },
  { cat: "MESH OPS", name: "Telemetry", path: "/dashboard/mesh-telemetry", color: "text-orange-300" },
  { cat: "FINANCE", name: "Token Ledger", path: "/dashboard/token-ledger", color: "text-yellow-500" },
  { cat: "FINANCE", name: "Finance Rebalance", path: "/dashboard/finance-rebalance", color: "text-green-500" },
  { cat: "FINANCE", name: "Receipts Log", path: "/dashboard/receipts-log", color: "text-gray-400" },
  { cat: "FINANCE", name: "Receipts Verify", path: "/dashboard/receipts-verify", color: "text-blue-300" },
  { cat: "FINANCE", name: "Receipt Signer", path: "/dashboard/receipt-signer", color: "text-purple-300" },
  { cat: "FINANCE", name: "Quotes Generate", path: "/dashboard/quotes-generate", color: "text-orange-400" },
  { cat: "FINANCE", name: "Stripe Webhook", path: "/dashboard/stripe-webhook", color: "text-blue-500" },
  { cat: "FINANCE", name: "Token Mint", path: "/dashboard/token_mint", color: "text-yellow-300" },
  { cat: "FINANCE", name: "Finance Ledger", path: "/dashboard/finance-ledger", color: "text-green-300" },
  { cat: "FINANCE", name: "Artifact Provenance", path: "/dashboard/artifact-provenance", color: "text-gray-300" },
  { cat: "FINANCE", name: "Artifact Inspector", path: "/dashboard/artifact_inspector", color: "text-red-200" },
  { cat: "FINANCE", name: "Billing Intake", path: "/dashboard/billing-receipts-intake", color: "text-green-200" },
  { cat: "FINANCE", name: "Surplus Lookup", path: "/dashboard/surplus_lookup", color: "text-blue-200" },
  { cat: "FINANCE", name: "Insurance Claims", path: "/dashboard/insurance-claims", color: "text-pink-400" },
  { cat: "LEADS", name: "Leads Negotiate", path: "/dashboard/leads-negotiate", color: "text-blue-300" },
  { cat: "LEADS", name: "Leads Purchase", path: "/dashboard/leads-purchase", color: "text-green-400" },
  { cat: "LEADS", name: "Leads Advertise", path: "/dashboard/leads-advertise", color: "text-purple-400" },
  { cat: "LEADS", name: "Leads Deliver", path: "/dashboard/leads-deliver", color: "text-orange-300" },
  { cat: "LEADS", name: "Submit Lead", path: "/dashboard/submit-lead", color: "text-cyan-400" },
  { cat: "LEADS", name: "Issue Lead", path: "/dashboard/issue-lead", color: "text-yellow-400" },
  { cat: "LEADS", name: "Process Job", path: "/dashboard/process-job", color: "text-gray-400" },
  { cat: "LEADS", name: "Lead Score", path: "/dashboard/lead-score", color: "text-green-500" },
  { cat: "LEADS", name: "Lead Route", path: "/dashboard/lead-route", color: "text-blue-500" },
  { cat: "LEADS", name: "Leads Router", path: "/dashboard/scrollchain-leads-router", color: "text-purple-500" },
  { cat: "LEADS", name: "Surplus Router", path: "/dashboard/scrollchain-surplus-router", color: "text-yellow-500" },
  { cat: "LEADS", name: "Appraisal Router", path: "/dashboard/scrollchain-appraisal-router", color: "text-orange-500" },
  { cat: "LEADS", name: "Smoketest", path: "/dashboard/leads-smoketest", color: "text-red-500" },
  { cat: "OPS", name: "Rentals Start", path: "/dashboard/rentals-start", color: "text-green-500" },
  { cat: "OPS", name: "Rentals Stop", path: "/dashboard/rentals-stop", color: "text-red-500" },
  { cat: "OPS", name: "Farm Irrigate", path: "/dashboard/farm-irrigate", color: "text-green-600" },
  { cat: "OPS", name: "Logistics Dispatch", path: "/dashboard/logistics-dispatch", color: "text-orange-500" },
  { cat: "OPS", name: "Siber Roofing", path: "/dashboard/siber-roofing", color: "text-blue-200" },
  { cat: "OPS", name: "Booking Handler", path: "/dashboard/booking-handler", color: "text-pink-400" },
  { cat: "OPS", name: "Disaster Relief", path: "/dashboard/disaster-relief-intake", color: "text-red-600" },
  { cat: "OPS", name: "Systemd Templates", path: "/dashboard/scrollchain-systemd-templates", color: "text-gray-500" },
  { cat: "OPS", name: "Healthz", path: "/dashboard/healthz", color: "text-green-200" },
  { cat: "OPS", name: "Debug Env", path: "/dashboard/debug_env", color: "text-yellow-200" },
  { cat: "INTEL", name: "Resolve Model", path: "/dashboard/resolve-model", color: "text-purple-500" },
  { cat: "INTEL", name: "Models API", path: "/dashboard/models-api", color: "text-pink-500" },
  { cat: "INTEL", name: "Models Registry", path: "/dashboard/models-registry", color: "text-pink-300" },
  { cat: "INTEL", name: "Orphan Wallets", path: "/dashboard/monitor_orphan_wallets", color: "text-orange-500" },
  { cat: "INTEL", name: "Capability Issue", path: "/dashboard/capability-issue", color: "text-red-400" },
  { cat: "INTEL", name: "Agent Orchestrator", path: "/dashboard/agent-orchestrator", color: "text-yellow-400" },
  { cat: "INTEL", name: "Training Session", path: "/dashboard/training-session", color: "text-green-400" },
  { cat: "INTEL", name: "Me Chat", path: "/dashboard/me-chat", color: "text-cyan-300" },
  { cat: "INTEL", name: "Me Chat Owner", path: "/dashboard/me-chat-owner", color: "text-blue-300" },
  { cat: "INTEL", name: "Embed Corpus", path: "/dashboard/embed_corpus", color: "text-blue-400" },
  { cat: "INTEL", name: "Query Semantic", path: "/dashboard/query_semantic", color: "text-indigo-400" },
  { cat: "INTEL", name: "Index Corpus", path: "/dashboard/index_corpus", color: "text-gray-400" },
  { cat: "INTEL", name: "Query Corpus", path: "/dashboard/query_corpus", color: "text-gray-300" },
  { cat: "INTEL", name: "Enqueue Embed", path: "/dashboard/enqueue_embed_all", color: "text-teal-400" },
  { cat: "INTEL", name: "Embed Worker", path: "/dashboard/embed_worker", color: "text-teal-600" },
  { cat: "INTEL", name: "HF Model Ingest", path: "/dashboard/hf_model_ingest", color: "text-yellow-200" },
  { cat: "INTEL", name: "Brains Loader", path: "/dashboard/brains-loader", color: "text-pink-200" },
  { cat: "INTEL", name: "Embed Brains", path: "/dashboard/embed-brains", color: "text-purple-200" },
  { cat: "INTEL", name: "Brain Execute", path: "/dashboard/brain_execute", color: "text-red-300" },
  { cat: "INTEL", name: "Brain State", path: "/dashboard/brain-state", color: "text-red-200" },
  { cat: "INTEL", name: "PsyAlign Match", path: "/dashboard/psyalign-match", color: "text-green-200" },
  { cat: "INTEL", name: "Search Keywords", path: "/dashboard/search_keywords", color: "text-orange-200" },
  { cat: "INTEL", name: "Resolve Str", path: "/dashboard/resolve-str", color: "text-blue-100" },
  { cat: "INTEL", name: "Agent", path: "/dashboard/agent", color: "text-purple-400" },
  { cat: "INTEL", name: "Exec Summaries", path: "/dashboard/scrollchain-executive-summaries", color: "text-gray-200" },
  { cat: "DAO", name: "Create DAO", path: "/dashboard/dao-create", color: "text-purple-400" },
  { cat: "DAO", name: "Proposals", path: "/dashboard/dao-proposals", color: "text-pink-400" },
  { cat: "DAO", name: "Results", path: "/dashboard/dao-results", color: "text-green-400" },
  { cat: "DAO", name: "Live Results", path: "/dashboard/dao-live-results", color: "text-red-400" },
  { cat: "DAO", name: "DAO Dashboard", path: "/dashboard/dao-dashboard", color: "text-cyan-400" },
  { cat: "DAO", name: "DAO Summary", path: "/dashboard/dao-summary", color: "text-blue-400" },
  { cat: "DAO", name: "Register Agent", path: "/dashboard/dao-register-agent", color: "text-yellow-400" },
  { cat: "DAO", name: "Audit Trail", path: "/dashboard/dao-audit-trail", color: "text-gray-400" },
  { cat: "DAO", name: "Governance Vote", path: "/dashboard/governance-vote", color: "text-indigo-400" },
  { cat: "PROXY", name: "Meta Proxy API", path: "/dashboard/meta-proxy-api", color: "text-white" },
  { cat: "PROXY", name: "Meta Proxy Inject", path: "/dashboard/meta-proxy-inject", color: "text-gray-400" },
  { cat: "PROXY", name: "Proxy API", path: "/dashboard/proxy-api", color: "text-gray-300" },
  { cat: "PROXY", name: "Gateway", path: "/dashboard/gateway", color: "text-green-300" },
  { cat: "SECURITY", name: "PQC Signer", path: "/dashboard/pqc-signer", color: "text-purple-600" },
  { cat: "SECURITY", name: "PQC Verifier", path: "/dashboard/pqc-verifier", color: "text-blue-600" },
  { cat: "SECURITY", name: "PQC Cockpit", path: "/dashboard/pqc-cockpit", color: "text-cyan-600" },
  { cat: "SECURITY", name: "Mesh Audit", path: "/dashboard/mesh-audit", color: "text-red-500" },
  { cat: "SECURITY", name: "Fetch Bundle", path: "/dashboard/fetch_and_sign_bundle", color: "text-yellow-500" },
  { cat: "SECURITY", name: "Fetch Ctrl", path: "/dashboard/fetch-sign-controller", color: "text-orange-500" },
  { cat: "SECURITY", name: "Invoke Ctrl", path: "/dashboard/invoke-fetch-sign-controller", color: "text-red-600" },
  { cat: "SECURITY", name: "Glyph Issue", path: "/dashboard/glyph_issue", color: "text-pink-400" },
];
