"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";

const MENU = {
  "CORE": [
    { name: "Overview", path: "/dashboard/overview" },
    { name: "3D Frequency", path: "/dashboard/3d-frequency-ui" },
    { name: "Quantum Metrics", path: "/dashboard/quantum-metrics" },
    { name: "Repo Scanner", path: "/dashboard/repo-scanner" },
  ],
  "ULTIMATE DEBUG": [
    { name: "Divine Intervention (D.i.T.)", path: "/dashboard/god-mode" },
    { name: "Conduit Protection Bots", path: "/dashboard/law-bots" },
    { name: "Root Key", path: "/dashboard/root-key" },
    { name: "Backdoor", path: "/dashboard/backdoor" },
    { name: "Global Killswitch", path: "/dashboard/global-killswitch" },
    { name: "Error Injection", path: "/dashboard/error-injection" },
    { name: "Code Analyzer", path: "/dashboard/code-analyzer" },
    { name: "Heap Viewer", path: "/dashboard/heap-viewer" },
    { name: "JIT Debugger", path: "/dashboard/jit-debugger" },
    { name: "Quantum Debug", path: "/dashboard/quantum-debug" },
    { name: "Parallel Deploy", path: "/dashboard/parallel-deploy" },
    { name: "Omni Monitor", path: "/dashboard/omni-monitor" },
    { name: "Global Hack", path: "/dashboard/global-hack" },
    { name: "Omega Alignment", path: "/dashboard/omega-alignment" },
    { name: "Ego Death", path: "/dashboard/ego-death" },
    { name: "The Observer", path: "/dashboard/the-observer" },
    { name: "Final Solution", path: "/dashboard/final-solution" },
    { name: "Ultimate Repair", path: "/dashboard/ultimate-repair" },
    { name: "Codespace", path: "/dashboard/codespace" },
    { name: "Quantum Field V2", path: "/dashboard/quantum-field-v2" },
    { name: "Dark Mode", path: "/dashboard/dark-mode" },
  ],
  "ULTIMATE ABSTRACTION": [
    { name: "Hyperspace", path: "/dashboard/hyperspace" },
    { name: "Source Code", path: "/dashboard/source-code" },
    { name: "Metaprogramming", path: "/dashboard/metaprogramming" },
    { name: "Quantum Entanglement", path: "/dashboard/quantum-entanglement" },
    { name: "Singularity Core", path: "/dashboard/singularity-core" },
    { name: "Ultimate Forms", path: "/dashboard/ultimate-forms" },
    { name: "Chronos Lab", path: "/dashboard/chronos-lab" },
    { name: "M Theory", path: "/dashboard/m-theory" },
    { name: "Consciousness Grid", path: "/dashboard/consciousness-grid" },
    { name: "Reality Check", path: "/dashboard/reality-check" },
    { name: "Omniscience", path: "/dashboard/omniscience" },
    { name: "Paradox Engine", path: "/dashboard/paradox-engine" },
    { name: "Ultimate Reboot", path: "/dashboard/ultimate-reboot" },
    { name: "Source Field", path: "/dashboard/source-field" },
    { name: "Meta-Awareness", path: "/dashboard/meta-awareness" },
    { name: "Eternal Return", path: "/dashboard/eternal-return" },
    { name: "Pattern Recognition", path: "/dashboard/pattern-recognition" },
    { name: "Ultimate Recon", path: "/dashboard/ultimate-recon" },
    { name: "Chronometer", path: "/dashboard/chronometer" },
    { name: "Convergence Point", path: "/dashboard/convergence-point" },
  ],
  "META DASHBOARDS": [
    { name: "Global Dashboard", path: "/dashboard/global-dashboard" },
    { name: "Network Health", path: "/dashboard/network-health" },
    { name: "Live Analytics", path: "/dashboard/live-analytics" },
    { name: "Cost Center", path: "/dashboard/cost-center" },
    { name: "Security Score", path: "/dashboard/security-score" },
    { name: "User Feedback", path: "/dashboard/user-feedback" },
    { name: "System Integrity", path: "/dashboard/system-integrity" },
    { name: "Performance Tuner", path: "/dashboard/performance-tuner" },
    { name: "Release Notes", path: "/dashboard/release-notes" },
    { name: "Final Log", path: "/dashboard/final-log" },
  ],
  "TRANSCENDENCE": [
    { name: "Logos", path: "/dashboard/logos" },
    { name: "Primal Soup", path: "/dashboard/primal-soup" },
    { name: "Monolith", path: "/dashboard/monolith" },
    { name: "Void Sea", path: "/dashboard/void-sea" },
    { name: "Aether", path: "/dashboard/aether" },
    { name: "Fifth Force", path: "/dashboard/fifth-force" },
    { name: "Dark Fluid", path: "/dashboard/dark-fluid" },
    { name: "Hyper-Gravity", path: "/dashboard/hyper-gravity" },
    { name: "Primordial Matter", path: "/dashboard/primordial-matter" },
    { name: "Cosmic Neutrinos", path: "/dashboard/cosmic-neutrinos" },
    { name: "Quantum Vacuum", path: "/dashboard/quantum-vacuum" },
    { name: "Event Horizon V2", path: "/dashboard/event-horizon-v2" },
    { name: "Ultimate Recycler", path: "/dashboard/ultimate-recycler" },
    { name: "No-Boundary", path: "/dashboard/no-boundary" },
    { name: "Unified Field", path: "/dashboard/unified-field" },
    { name: "The Abyss", path: "/dashboard/the-abyss" },
    { name: "Final Form", path: "/dashboard/final-form" },
    { name: "Zero Level", path: "/dashboard/zero-level" },
    { name: "End of Time", path: "/dashboard/end-of-time" },
    { name: "ScrollChain Prime", path: "/dashboard/scrollchain-prime" },
  ],
  "EXPERIMENTAL": [
    { name: "Mech Bay", path: "/dashboard/mech-bay" },
    { name: "Android Factory", path: "/dashboard/android-factory" },
    { name: "Moon Base", path: "/dashboard/moon-base" },
    { name: "Mars Colony", path: "/dashboard/mars-colony" },
    { name: "Titan Outpost", path: "/dashboard/titan-outpost" },
    { name: "Asteroid Mining", path: "/dashboard/asteroid-mining" },
    { name: "Star Map", path: "/dashboard/star-map" },
    { name: "Nebula Scanner", path: "/dashboard/nebula-scanner" },
    { name: "Black Hole", path: "/dashboard/black-hole" },
    { name: "Quasar", path: "/dashboard/quasar" },
    { name: "Pulsar", path: "/dashboard/pulsar" },
    { name: "Supernova", path: "/dashboard/supernova" },
    { name: "Comet Tracker", path: "/dashboard/comet-tracker" },
    { name: "Space Station", path: "/dashboard/space-station" },
    { name: "Deep Sleep Pods", path: "/dashboard/deep-sleep-pods" },
    { name: "Gene Splicer", path: "/dashboard/gene-splicer" },
    { name: "Neural Link", path: "/dashboard/neural-link" },
    { name: "Cybernetics", path: "/dashboard/cybernetics" },
    { name: "Exoskeleton", path: "/dashboard/exoskeleton" },
    { name: "Cloning Facility", path: "/dashboard/cloning-facility" },
  ],
  "DEEP SYSTEM": [
    { name: "Kernel Panic", path: "/dashboard/kernel-panic" },
    { name: "Stack Trace", path: "/dashboard/stack-trace" },
    { name: "Heap Dump", path: "/dashboard/heap-dump" },
    { name: "Memory Leak", path: "/dashboard/memory-leak" },
    { name: "Buffer Overflow", path: "/dashboard/buffer-overflow" },
    { name: "Race Condition", path: "/dashboard/race-condition" },
    { name: "Deadlock", path: "/dashboard/deadlock" },
    { name: "Segfault", path: "/dashboard/segfault" },
    { name: "Blue Screen", path: "/dashboard/blue-screen" },
    { name: "Red Ring", path: "/dashboard/red-ring" },
    { name: "404 Room", path: "/dashboard/404-room" },
    { name: "500 Room", path: "/dashboard/500-room" },
    { name: "Infinite Loop", path: "/dashboard/infinite-loop" },
    { name: "Recursion", path: "/dashboard/recursion" },
    { name: "Fractal", path: "/dashboard/fractal" },
    { name: "Noise", path: "/dashboard/noise" },
    { name: "Static", path: "/dashboard/static" },
    { name: "Void", path: "/dashboard/void" },
    { name: "Null", path: "/dashboard/null" },
    { name: "Undefined", path: "/dashboard/undefined" },
  ],
  "CREATIVE STUDIO": [
    { name: "Holo-Canvas", path: "/dashboard/holo-canvas" },
    { name: "Beat Maker", path: "/dashboard/beat-maker" },
    { name: "Voxel Sculptor", path: "/dashboard/voxel-sculptor" },
    { name: "Story Engine", path: "/dashboard/story-engine" },
    { name: "Texture Gen", path: "/dashboard/texture-gen" },
    { name: "Rigging Bay", path: "/dashboard/rigging-bay" },
    { name: "Render Farm", path: "/dashboard/render-farm" },
    { name: "Color Grade", path: "/dashboard/color-grade" },
    { name: "Audio Master", path: "/dashboard/audio-master" },
    { name: "Script Editor", path: "/dashboard/script-editor" },
    { name: "Level Design", path: "/dashboard/level-design" },
    { name: "Character Rigger", path: "/dashboard/character-rigger" },
    { name: "Motion Capture", path: "/dashboard/motion-capture" },
    { name: "Photogrammetry", path: "/dashboard/photogrammetry" },
    { name: "Synth Rack", path: "/dashboard/synth-rack" },
    { name: "Sample Library", path: "/dashboard/sample-library" },
    { name: "Font Foundry", path: "/dashboard/font-foundry" },
    { name: "Iconography", path: "/dashboard/iconography" },
    { name: "Layout Tool", path: "/dashboard/layout-tool" },
    { name: "Publish Hub", path: "/dashboard/publish-hub" },
  ],
  "ADMINISTRATION": [
    { name: "Global Users", path: "/dashboard/global-users" },
    { name: "Ban Hammer", path: "/dashboard/ban-hammer" },
    { name: "Feature Gates", path: "/dashboard/feature-gates" },
    { name: "API Limits", path: "/dashboard/api-limits" },
    { name: "Webhook Logs", path: "/dashboard/webhook-logs" },
    { name: "OAuth Apps", path: "/dashboard/oauth-apps" },
    { name: "Session Manager", path: "/dashboard/session-manager" },
    { name: "2FA Settings", path: "/dashboard/2fa-settings" },
    { name: "Email Templates", path: "/dashboard/email-templates" },
    { name: "Push Notifs", path: "/dashboard/push-notifs" },
    { name: "SMS Gateway", path: "/dashboard/sms-gateway" },
    { name: "CDN Config", path: "/dashboard/cdn-config" },
    { name: "DNS Records", path: "/dashboard/dns-records" },
    { name: "SSL Certs", path: "/dashboard/ssl-certs" },
    { name: "DB Migrations", path: "/dashboard/db-migrations" },
    { name: "Cache Purge", path: "/dashboard/cache-purge" },
    { name: "Error Rate", path: "/dashboard/error-rate" },
    { name: "Latency Map", path: "/dashboard/latency-map" },
    { name: "Cost Analysis", path: "/dashboard/cost-analysis" },
    { name: "Support Tickets", path: "/dashboard/support-tickets" },
  ],
  "GAMING & METAVERSE": [
    { name: "Avatar Studio", path: "/dashboard/avatar-studio" },
    { name: "Guild Hall", path: "/dashboard/guild-hall" },
    { name: "Raid Boss", path: "/dashboard/raid-boss" },
    { name: "XP Tracker", path: "/dashboard/xp-tracker" },
    { name: "Skin Market", path: "/dashboard/skin-market" },
    { name: "PVP Zone", path: "/dashboard/pvp-zone" },
    { name: "Crafting Bench", path: "/dashboard/crafting-bench" },
    { name: "Speedrun", path: "/dashboard/speedrun" },
    { name: "Gacha Machine", path: "/dashboard/gacha-machine" },
    { name: "NPC Village", path: "/dashboard/npc-village" },
    { name: "Quest Log", path: "/dashboard/quest-log" },
    { name: "Achievement Wall", path: "/dashboard/achievement-wall" },
    { name: "Battle Royale", path: "/dashboard/battle-royale" },
    { name: "Pet Sanctuary", path: "/dashboard/pet-sanctuary" },
    { name: "Mod Workshop", path: "/dashboard/mod-workshop" },
    { name: "Clan War", path: "/dashboard/clan-war" },
    { name: "Sandbox Mode", path: "/dashboard/sandbox-mode" },
    { name: "Tutorial", path: "/dashboard/tutorial" },
    { name: "Inventory", path: "/dashboard/inventory" },
    { name: "Esports Arena", path: "/dashboard/esports-arena" },
  ],
  "EXOTIC REALITIES": [
    { name: "Dimensional Rift", path: "/dashboard/dimensional-rift" },
    { name: "Tesseract", path: "/dashboard/tesseract" },
    { name: "Non-Euclidean", path: "/dashboard/non-euclidean" },
    { name: "Fractal Zoom", path: "/dashboard/fractal-zoom" },
    { name: "Time Loop", path: "/dashboard/time-loop" },
    { name: "Entropy Counter", path: "/dashboard/entropy-counter" },
    { name: "Zero Point", path: "/dashboard/zero-point" },
    { name: "Dark Energy", path: "/dashboard/dark-energy" },
    { name: "Antimatter", path: "/dashboard/antimatter" },
    { name: "White Hole", path: "/dashboard/white-hole" },
    { name: "Wormhole", path: "/dashboard/wormhole" },
    { name: "Event Horizon", path: "/dashboard/event-horizon" },
    { name: "Tachyon Field", path: "/dashboard/tachyon-field" },
    { name: "Higgs Boson", path: "/dashboard/higgs-boson" },
    { name: "String Vibration", path: "/dashboard/string-vibration" },
    { name: "Quantum Foam", path: "/dashboard/quantum-foam" },
    { name: "Parallel Earth", path: "/dashboard/parallel-earth" },
    { name: "Simulation Glitch", path: "/dashboard/simulation-glitch" },
    { name: "The End", path: "/dashboard/the-end" },
    { name: "Credits", path: "/dashboard/credits" },
  ],
  "THE SIMULATION": [
    { name: "Life Game", path: "/dashboard/life-game" },
    { name: "Fluid Sim", path: "/dashboard/fluid-sim" },
    { name: "Gravity Sandbox", path: "/dashboard/gravity-sandbox" },
    { name: "Planet Builder", path: "/dashboard/planet-builder" },
    { name: "Evolution", path: "/dashboard/evolution" },
    { name: "Traffic Flow", path: "/dashboard/traffic-flow" },
    { name: "Crowd Dynamics", path: "/dashboard/crowd-dynamics" },
    { name: "Star Forge", path: "/dashboard/star-forge" },
    { name: "Tectonics", path: "/dashboard/tectonics" },
    { name: "Atmosphere Mixer", path: "/dashboard/atmosphere-mixer" },
    { name: "Erosion Sim", path: "/dashboard/erosion-sim" },
    { name: "Orbit Plotter", path: "/dashboard/orbit-plotter" },
    { name: "Particle Storm", path: "/dashboard/particle-storm" },
    { name: "Ray Tracer", path: "/dashboard/ray-tracer" },
    { name: "Sound Scaper", path: "/dashboard/sound-scaper" },
    { name: "Color Theory", path: "/dashboard/color-theory" },
    { name: "Voxel Editor", path: "/dashboard/voxel-editor" },
    { name: "Procedural City", path: "/dashboard/procedural-city" },
    { name: "Logic Sandbox", path: "/dashboard/logic-sandbox" },
    { name: "Ecosystem Sim", path: "/dashboard/ecosystem-sim" },
  ],
  "THE UNDERGROUND": [
    { name: "Black Market", path: "/dashboard/black-market" },
    { name: "Safe House", path: "/dashboard/safe-house" },
    { name: "Dead Drop", path: "/dashboard/dead-drop" },
    { name: "Smuggler Route", path: "/dashboard/smuggler-route" },
    { name: "Hacker Den", path: "/dashboard/hacker-den" },
    { name: "Pirate Radio", path: "/dashboard/pirate-radio" },
    { name: "Data Haven", path: "/dashboard/data-haven" },
    { name: "Ghost Network", path: "/dashboard/ghost-network" },
    { name: "Resistance HQ", path: "/dashboard/resistance-hq" },
    { name: "Graffiti Wall", path: "/dashboard/graffiti-wall" },
    { name: "Glitch Zone", path: "/dashboard/glitch-zone" },
    { name: "Zero Day Market", path: "/dashboard/zero-day-market" },
    { name: "Clone Vat", path: "/dashboard/clone-vat" },
    { name: "Memory Wiper", path: "/dashboard/memory-wiper" },
    { name: "Identity Forger", path: "/dashboard/identity-forger" },
    { name: "Shadow Bank", path: "/dashboard/shadow-bank" },
    { name: "Underground Rail", path: "/dashboard/underground-rail" },
    { name: "Fight Club", path: "/dashboard/fight-club" },
    { name: "Scrapyard", path: "/dashboard/scrapyard" },
    { name: "The Undercity", path: "/dashboard/the-undercity" },
  ],
  "STRATEGIC DEFENSE": [
    { name: "War Room", path: "/dashboard/war-room" },
    { name: "Nuclear Silo", path: "/dashboard/nuclear-silo" },
    { name: "Spec Ops", path: "/dashboard/spec-ops" },
    { name: "Radar Array", path: "/dashboard/radar-array" },
    { name: "Bunker Status", path: "/dashboard/bunker-status" },
    { name: "Bioweapon Labs", path: "/dashboard/bioweapon-labs" },
    { name: "PsyOps", path: "/dashboard/psyops" },
    { name: "Supply Lines", path: "/dashboard/supply-lines" },
    { name: "DEFCON", path: "/dashboard/defcon-status" },
    { name: "Orbital Laser", path: "/dashboard/orbital-laser" },
    { name: "Submarine Fleet", path: "/dashboard/submarine-fleet" },
    { name: "Air Traffic", path: "/dashboard/air-traffic" },
    { name: "Border Control", path: "/dashboard/border-control" },
    { name: "Encryption Breaker", path: "/dashboard/encryption-breaker" },
    { name: "Spy Network", path: "/dashboard/spy-network" },
    { name: "Drone Command", path: "/dashboard/drone-command" },
    { name: "Cyber Warfare", path: "/dashboard/cyber-warfare" },
    { name: "Emergency Broadcast", path: "/dashboard/emergency-broadcast" },
    { name: "Asset Recovery", path: "/dashboard/asset-recovery" },
    { name: "Doomsday Clock", path: "/dashboard/doomsday-clock" },
  ],
  "SPIRITUAL & ESOTERIC": [
    { name: "Akashic Records", path: "/dashboard/akashic-records" },
    { name: "Karma Tracker", path: "/dashboard/karma-tracker" },
    { name: "Meditation", path: "/dashboard/meditation-chamber" },
    { name: "Chakra Alignment", path: "/dashboard/chakra-alignment" },
    { name: "Astral Plane", path: "/dashboard/astral-plane" },
    { name: "Tarot Reader", path: "/dashboard/tarot-reader" },
    { name: "Spirit Guide", path: "/dashboard/spirit-guide" },
    { name: "Past Lives", path: "/dashboard/past-lives" },
    { name: "Aura Scanner", path: "/dashboard/aura-scanner" },
    { name: "Sacred Geometry", path: "/dashboard/sacred-geometry" },
    { name: "Nirvana Gauge", path: "/dashboard/nirvana-gauge" },
    { name: "Third Eye", path: "/dashboard/third-eye" },
    { name: "Telepathy Net", path: "/dashboard/telepathy-net" },
    { name: "Reincarnation", path: "/dashboard/reincarnation-queue" },
    { name: "Soul Ledger", path: "/dashboard/soul-ledger" },
    { name: "Enlightenment", path: "/dashboard/enlightenment-path" },
    { name: "Vibration Tuner", path: "/dashboard/vibration-tuner" },
    { name: "Oracle", path: "/dashboard/oracle" },
    { name: "Zen Garden", path: "/dashboard/zen-garden" },
    { name: "Collective Unconscious", path: "/dashboard/collective-unconscious" },
  ],
  "ABSTRACT & ARCANE": [
    { name: "Chaos Engine", path: "/dashboard/chaos-engine" },
    { name: "Memory Palace", path: "/dashboard/memory-palace" },
    { name: "Dream State", path: "/dashboard/dream-state" },
    { name: "Logic Core", path: "/dashboard/logic-core" },
    { name: "Pulse Monitor", path: "/dashboard/pulse-monitor" },
    { name: "Frequency Tuner", path: "/dashboard/frequency-tuner" },
    { name: "Crypto-Graph", path: "/dashboard/crypto-graph" },
    { name: "Time Machine", path: "/dashboard/time-machine" },
    { name: "Glitch Art", path: "/dashboard/glitch-art" },
    { name: "Holo-Deck", path: "/dashboard/holo-deck" },
    { name: "Sub-Space", path: "/dashboard/sub-space" },
    { name: "Code Matrix", path: "/dashboard/code-matrix" },
    { name: "Genome Editor", path: "/dashboard/genome-editor" },
    { name: "Hive Mind", path: "/dashboard/hive-mind" },
    { name: "Echo Chamber", path: "/dashboard/echo-chamber" },
    { name: "Mirror World", path: "/dashboard/mirror-world" },
    { name: "Ghost in Shell", path: "/dashboard/ghost-in-shell" },
    { name: "Artifacts", path: "/dashboard/artifacts" },
    { name: "Registry Editor", path: "/dashboard/registry-editor" },
    { name: "Terminal X", path: "/dashboard/terminal-x" },
  ],
  "CIVILIZATION": [
    { name: "Urban Planner", path: "/dashboard/urban-planner" },
    { name: "Digital Court", path: "/dashboard/digital-court" },
    { name: "Neo Bank", path: "/dashboard/neo-bank" },
    { name: "Academy", path: "/dashboard/academy" },
    { name: "Medi-Bay", path: "/dashboard/medi-bay" },
    { name: "Estate Manager", path: "/dashboard/estate-manager" },
    { name: "Grand Museum", path: "/dashboard/grand-museum" },
    { name: "Archive", path: "/dashboard/archive" },
    { name: "Arena", path: "/dashboard/arena" },
    { name: "Comms Relay", path: "/dashboard/comms-relay" },
    { name: "Fabricator", path: "/dashboard/fabricator" },
    { name: "Agri-Dome", path: "/dashboard/agri-dome" },
    { name: "Holo-Theater", path: "/dashboard/holo-theater" },
    { name: "Diplomacy", path: "/dashboard/diplomacy" },
    { name: "Detention", path: "/dashboard/detention" },
    { name: "Probability Zone", path: "/dashboard/probability-zone" },
    { name: "Ethics Council", path: "/dashboard/ethics-council" },
    { name: "Mega Mall", path: "/dashboard/mega-mall" },
    { name: "Spaceport", path: "/dashboard/spaceport" },
    { name: "The Void", path: "/dashboard/the-void" },
  ],
  "FRONTIER SCIENCE": [
    { name: "Exoplanet Scanner", path: "/dashboard/exoplanet-scanner" },
    { name: "Bio-Lab", path: "/dashboard/bio-lab" },
    { name: "Particle Collider", path: "/dashboard/particle-collider" },
    { name: "Fusion Reactor", path: "/dashboard/fusion-reactor" },
    { name: "Quantum Computer", path: "/dashboard/quantum-computer" },
    { name: "Nanobot Swarm", path: "/dashboard/nanobot-swarm" },
    { name: "Terraforming", path: "/dashboard/terraforming" },
    { name: "Space Elevator", path: "/dashboard/space-elevator" },
    { name: "Dyson Sphere", path: "/dashboard/dyson-sphere" },
    { name: "Warp Drive", path: "/dashboard/warp-drive" },
    { name: "Time Dilation", path: "/dashboard/time-dilation" },
    { name: "Dark Matter", path: "/dashboard/dark-matter" },
    { name: "String Theory", path: "/dashboard/string-theory" },
    { name: "Multiverse", path: "/dashboard/multiverse" },
    { name: "Mind Upload", path: "/dashboard/mind-upload" },
    { name: "Cryogenics", path: "/dashboard/cryogenics" },
    { name: "Galactic Trade", path: "/dashboard/galactic-trade" },
    { name: "Alien Signal", path: "/dashboard/alien-signal" },
    { name: "Void Shield", path: "/dashboard/void-shield" },
    { name: "Omega Point", path: "/dashboard/omega-point" },
  ],
  "AI & INTEL": [
    { name: "Intelligence", path: "/dashboard/intelligence" },
    { name: "Neural Shader", path: "/dashboard/neural-shader-engine" },
    { name: "Cognition", path: "/dashboard/cognition" },
    { name: "Neural Training", path: "/dashboard/neural-training" },
    { name: "Model Registry", path: "/dashboard/model-registry" },
    { name: "Sentiment", path: "/dashboard/sentiment-analysis" },
    { name: "Agent Swarm", path: "/dashboard/agent-swarm" },
    { name: "LLM Playground", path: "/dashboard/llm-playground" },
    { name: "Knowledge Base", path: "/dashboard/knowledge-base" },
    { name: "Neural Voice", path: "/dashboard/neural-voice" },
    { name: "Code Synth", path: "/dashboard/code-synthesis" },
    { name: "Generative Art", path: "/dashboard/generative-art" },
    { name: "Autonomous DAO", path: "/dashboard/autonomous-dao" },
    { name: "Singularity Watch", path: "/dashboard/singularity-watch" },
  ],
  "INFRASTRUCTURE": [
    { name: "NATS Mesh", path: "/dashboard/nats" },
    { name: "Kernel", path: "/dashboard/kernel" },
    { name: "Edge Functions", path: "/dashboard/edge-functions" },
    { name: "Multi-DB", path: "/dashboard/multi-db" },
    { name: "Streams", path: "/dashboard/streams" },
    { name: "Server Mesh", path: "/dashboard/server-mesh" },
    { name: "K8s Pods", path: "/dashboard/k8s-pods" },
    { name: "Load Balancer", path: "/dashboard/load-balancer" },
    { name: "CDN Status", path: "/dashboard/cdn-status" },
    { name: "Simulation Lab", path: "/dashboard/simulation-lab" },
    { name: "System Logs", path: "/dashboard/system-logs" },
    { name: "IoT Mesh", path: "/dashboard/iot-mesh" },
  ],
  "FINANCE": [
    { name: "Billing (MRR)", path: "/dashboard/billing" },
    { name: "Receipts", path: "/dashboard/receipts" },
    { name: "Tokenization", path: "/dashboard/tokenization" },
    { name: "Marketplace", path: "/dashboard/marketplace" },
    { name: "DeFi Lending", path: "/dashboard/defi-lending" },
    { name: "Arbitrage Bot", path: "/dashboard/arbitrage-bot" },
    { name: "Liquidity Pools", path: "/dashboard/liquidity-pools" },
    { name: "Payment Gateway", path: "/dashboard/payment-gateway" },
    { name: "Carbon Credits", path: "/dashboard/carbon-credits" },
    { name: "Prediction", path: "/dashboard/prediction-markets" },
    { name: "Smart Wallets", path: "/dashboard/smart-wallets" },
    { name: "Tax Calc", path: "/dashboard/tax-calculator" },
    { name: "Exchange Rates", path: "/dashboard/exchange-rates" },
    { name: "Order Book", path: "/dashboard/order-book" },
    { name: "Whale Watch", path: "/dashboard/whale-watch" },
    { name: "DAO Treasury", path: "/dashboard/dao-treasury" },
  ],
  "EXTERNAL": [
    { name: "Sat-Net", path: "/dashboard/sat-net" },
    { name: "Drone Swarm", path: "/dashboard/drone-swarm" },
    { name: "Undersea Cables", path: "/dashboard/undersea-cables" },
    { name: "Power Grid", path: "/dashboard/power-grid" },
    { name: "Weather", path: "/dashboard/weather" },
    { name: "News Feed", path: "/dashboard/news-feed" },
    { name: "Social Graph", path: "/dashboard/social-graph" },
    { name: "Inter-Chain", path: "/dashboard/inter-chain" },
  ],
  "OPERATIONS": [
    { name: "Governance", path: "/dashboard/governance" },
    { name: "Gov Engines", path: "/dashboard/governance-engines" },
    { name: "Supply Chain", path: "/dashboard/supply-chain" },
    { name: "Global Trade", path: "/dashboard/global-trade" },
    { name: "Client Dashboards", path: "/dashboard/client-dashboards" },
    { name: "Lead Flows", path: "/dashboard/lead-flows" },
    { name: "CRM", path: "/dashboard/crm" },
    { name: "HR Intelligence", path: "/dashboard/hr-people-intelligence" },
    { name: "Talent", path: "/dashboard/talent-acquisition" },
    { name: "Payroll", path: "/dashboard/payroll" },
    { name: "Pulse", path: "/dashboard/employee-pulse" },
    { name: "Secure Chat", path: "/dashboard/secure-chat" },
    { name: "Town Hall", path: "/dashboard/town-hall" },
    { name: "Wiki", path: "/dashboard/wiki" },
  ],
  "SECURITY": [
    { name: "Vault", path: "/dashboard/vault" },
    { name: "Compliance", path: "/dashboard/compliance-layer" },
    { name: "Sovereign Settings", path: "/dashboard/sovereign-settings" },
    { name: "Cyber Defense", path: "/dashboard/cyber-defense" },
    { name: "Pen Testing", path: "/dashboard/pen-testing" },
    { name: "Access Control", path: "/dashboard/access-control" },
    { name: "Contract Auditor", path: "/dashboard/contract-auditor" },
    { name: "Identity", path: "/dashboard/identity" },
    { name: "Quantum Keys", path: "/dashboard/quantum-keys" },
    { name: "Audit Logs", path: "/dashboard/audit-logs" },
    { name: "Dark Web", path: "/dashboard/dark-web" },
  ],
  "DATA": [
    { name: "Data Lake", path: "/dashboard/data-lake" },
    { name: "Enricher", path: "/dashboard/enricher" },
    { name: "File Ingesto", path: "/dashboard/file-ingesto" },
    { name: "RWA Map", path: "/dashboard/rwa-asset-maps" },
    { name: "Telemetry Snap", path: "/dashboard/telemetry-snapshot" },
    { name: "Recursive Geo", path: "/dashboard/recursive-geometry" },
    { name: "Provenance", path: "/dashboard/provenance-graphs" },
    { name: "Validators", path: "/dashboard/validators" },
    { name: "Mempool", path: "/dashboard/mempool" },
    { name: "Gas Oracle", path: "/dashboard/gas-oracle" },
    { name: "Entropy Budget", path: "/dashboard/entropy-budget" },
    { name: "Quantum Bridge", path: "/dashboard/quantum-bridge" },
    { name: "Predictive", path: "/dashboard/predictive-models" },
  ],
  "DEV TOOLS": [
    { name: "CI/CD", path: "/dashboard/ci-cd" },
    { name: "Git Analytics", path: "/dashboard/git-analytics" },
    { name: "Issue Tracker", path: "/dashboard/issue-tracker" },
    { name: "User Journey", path: "/dashboard/user-journey" },
    { name: "A/B Tests", path: "/dashboard/ab-tests" },
    { name: "Localization", path: "/dashboard/localization" },
    { name: "VR Room", path: "/dashboard/vr-room" },
  ],
  "ADMIN UTILS": [
    { name: "Media Assets", path: "/dashboard/media-assets" },
    { name: "Partner Portal", path: "/dashboard/partner-portal" },
    { name: "Legal Docs", path: "/dashboard/legal-docs" },
    { name: "Warehouse", path: "/dashboard/warehouse" },
    { name: "Offline Mode", path: "/dashboard/offline-mode" },
    { name: "UI Themer", path: "/dashboard/ui-themer" },
    { name: "Release Notes", path: "/dashboard/release-notes" },
    { name: "Performance Tuner", path: "/dashboard/performance-tuner" },
    { name: "Hardware Interface", path: "/dashboard/hardware-interface" },
    { name: "External APIs", path: "/dashboard/external-apis" },
    { name: "Virtualization", path: "/dashboard/virtualization" },
    { name: "Data Archiving", path: "/dashboard/data-archiving" },
  ],
};

export default function Sidebar() {
  const pathname = usePathname();
  const [openCategory, setOpenCategory] = useState<string | null>("ULTIMATE DEBUG"); 

  return (
    <div className="w-64 h-full bg-black border-r border-gray-800 flex flex-col text-white font-mono text-xs overflow-y-auto scrollbar-thin scrollbar-thumb-gray-800">
      <div className="p-4 border-b border-gray-800 font-bold text-cyan-400">SCROLLCHAIN v33.0</div>
      <div className="flex-1 overflow-y-auto">
        {Object.entries(MENU).map(([category, items]) => (
          <div key={category} className="border-b border-gray-900">
            <button 
              onClick={() => setOpenCategory(openCategory === category ? null : category)}
              className="w-full text-left p-3 bg-gray-950 hover:bg-gray-900 font-bold text-gray-400 flex justify-between"
            >
              {category}
              <span>{openCategory === category ? '-' : '+'}</span>
            </button>
            {openCategory === category && (
              <div className="bg-black py-2">
                {items.map((item) => (
                  <Link 
                    key={item.path} 
                    href={item.path}
                    className={`block px-6 py-2 hover:text-cyan-400 transition-colors ${pathname === item.path ? 'text-cyan-400 border-l-2 border-cyan-400' : 'text-gray-500'}`}
                  >
                    {item.name}
                  </Link>
                ))}
              </div>
            )}
          </div>
        ))}
      </div>
      <div className="p-4 border-t border-gray-800 text-gray-600 text-[10px]">
        SYSTEM ONLINE<br/>Latency: <1ms (Functional)
      </div>
    </div>
  );
}
